### ISSUE TITLE
Package helper code for npm

### ISSUE THREAD

**Issue by mattgeddes** [versatus/versatus-javascript#1]
As we start to hone the interfaces in this code for writing smart contracts, we also need to refactor this repo into code packaged such that:
* It's able to be pulled in using the `npm` package manager
* The rest of the contract code (ie, anything contract-specific) is moved into example code that compiles and runs and is intuitive to JS developers

**Comment by hathbanger** [comment]
https://www.npmjs.com/package/@versatus/versatus-javascripta
