### ISSUE TITLE
Add an ERC20 interface to Javascript Kit

### ISSUE THREAD

**Issue by mattgeddes** [versatus/versatus-javascript#13]
Now that we have a basic set of inputs and outputs for Smart Contracts, we're looking to start to add more abstraction and simplicity on the various language kits. In this case, we want to define an interface (with as many compile time checks as possible) that allows a developer to quickly build an ERC20 token.

The Rust kit currently contains such an interface (https://github.com/versatus/versatus-rust/blob/main/src/versatus_rust.rs#L87). Although it isn't yet called from within the parsing/routing code and will soon. We want something similar for Go, Javascript, C, C++, Python and others. It is expected that there will be some consistency between all languages, but that language-ergonomics take precedence over being identical between language kits.

On instantiation of such a class or interface or whatever, there should be a constructor or convenience function/method for being able to switch within the contract to each of the different functions.

Here's more insight into the ERC20 standard: https://ethereum.org/en/developers/docs/standards/tokens/erc-20/

This task is to add this functionality to the Javascript kit in the versatus-javascript repo.

**Comment by hathbanger** [comment]
linking the current fungible:
https://github.com/versatus/versatus-javascript/blob/main/examples/fungible/example-program.ts

somewhat stale, closing
